name: main
on: [push]

jobs:
  rspec:
    strategy:
      matrix:
        php: [ ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php/setup-<<[lang]>>@v1
      with:
        php-version: ${{ matrix.<<[lang]>> }}
    - name: Build and test with
      run: |
